[package]
name = "tunka"
version = "0.2.3"
authors = ["xrelkd 46590321+xrelkd@users.noreply.github.com"]
edition = "2018"

[dependencies]
dirs = "2"
log = "0.4"
serde = { version = "1", features = [ "derive" ] }
serde_yaml = "0.8"
simple_logger = "1"
snafu = "0.6"
structopt = "0.3"
