[package]
name = "tunka"
version = "0.2.0"
authors = ["user <user@localhost>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "2"
failure = "0.1"
log = "0.4"
serde = { version = "1", features = [ "derive" ] }
serde_yaml = "0.8"
simple_logger = "1"
structopt = "0.3"
