complete -c tunka -n "__fish_use_subcommand" -l config-file -d 'Configuration file path'
complete -c tunka -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c tunka -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c tunka -n "__fish_use_subcommand" -f -a "list-tunnels" -d 'Shows available tunnels'
complete -c tunka -n "__fish_use_subcommand" -f -a "start" -d 'Starts a tunnel'
complete -c tunka -n "__fish_use_subcommand" -f -a "stop" -d 'Stops a tunnel'
complete -c tunka -n "__fish_use_subcommand" -f -a "restart" -d 'Restarts a tunnel'
complete -c tunka -n "__fish_use_subcommand" -f -a "running" -d 'Checks whether a tunnel is running'
complete -c tunka -n "__fish_use_subcommand" -f -a "start-all" -d 'Starts all available tunnels'
complete -c tunka -n "__fish_use_subcommand" -f -a "stop-all" -d 'Stops all available tunnels'
complete -c tunka -n "__fish_use_subcommand" -f -a "restart-all" -d 'Restarts all available tunnels'
complete -c tunka -n "__fish_use_subcommand" -f -a "version" -d 'Shows current version'
complete -c tunka -n "__fish_use_subcommand" -f -a "completions" -d 'Generates shell completion'
complete -c tunka -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c tunka -n "__fish_seen_subcommand_from list-tunnels" -s h -l help -d 'Prints help information'
complete -c tunka -n "__fish_seen_subcommand_from list-tunnels" -s V -l version -d 'Prints version information'
complete -c tunka -n "__fish_seen_subcommand_from start" -s h -l help -d 'Prints help information'
complete -c tunka -n "__fish_seen_subcommand_from start" -s V -l version -d 'Prints version information'
complete -c tunka -n "__fish_seen_subcommand_from stop" -s h -l help -d 'Prints help information'
complete -c tunka -n "__fish_seen_subcommand_from stop" -s V -l version -d 'Prints version information'
complete -c tunka -n "__fish_seen_subcommand_from restart" -s h -l help -d 'Prints help information'
complete -c tunka -n "__fish_seen_subcommand_from restart" -s V -l version -d 'Prints version information'
complete -c tunka -n "__fish_seen_subcommand_from running" -s h -l help -d 'Prints help information'
complete -c tunka -n "__fish_seen_subcommand_from running" -s V -l version -d 'Prints version information'
complete -c tunka -n "__fish_seen_subcommand_from start-all" -s h -l help -d 'Prints help information'
complete -c tunka -n "__fish_seen_subcommand_from start-all" -s V -l version -d 'Prints version information'
complete -c tunka -n "__fish_seen_subcommand_from stop-all" -s h -l help -d 'Prints help information'
complete -c tunka -n "__fish_seen_subcommand_from stop-all" -s V -l version -d 'Prints version information'
complete -c tunka -n "__fish_seen_subcommand_from restart-all" -s h -l help -d 'Prints help information'
complete -c tunka -n "__fish_seen_subcommand_from restart-all" -s V -l version -d 'Prints version information'
complete -c tunka -n "__fish_seen_subcommand_from version" -s h -l help -d 'Prints help information'
complete -c tunka -n "__fish_seen_subcommand_from version" -s V -l version -d 'Prints version information'
complete -c tunka -n "__fish_seen_subcommand_from completions" -s h -l help -d 'Prints help information'
complete -c tunka -n "__fish_seen_subcommand_from completions" -s V -l version -d 'Prints version information'
complete -c tunka -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c tunka -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
